### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/Image_restoration/LL_dataset/LOLv1/train/LOLv1_train.txt'

### ISSUE THREAD

**Issue by aimv-lab** [JianghaiSCU/Diffusion-Low-Light#12]
这个文件没有找到

**Comment by pengli-jc** [comment]
自己写一个，参考：
    img_folder = "LOLv1/eval15/low"
    paths = []
    for root, _, names in os.walk(img_folder):
        for name in names:
            path = os.path.join(root, name)
            path_gt = path.replace('low', 'high')
            if os.path.exists(path_gt):
                paths.append((path))
    
    save_path = "LOLv1_val.txt"
    with open(save_path, 'w') as f:
        for p1 in paths:
            f.write(f"{p1}")
            f.write('\n')

**Comment by jjjjjgggj** [comment]
老哥解决这个问题了吗，我也看不太懂

**Comment by lingxitong** [comment]
just write it as the format in dataset.py
