### ISSUE TITLE
Reproduce the code

### ISSUE THREAD

**Issue by lixiang4659** [JianghaiSCU/Diffusion-Low-Light#14]
What is the train.txt file in the evaluation.py?And the version of the packages in the requirements cannot be downloaded successfully?

**Comment by ciwei610** [comment]
I have the same question

**Comment by ciwei610** [comment]
Where did the LOLv1\\train\\LOLv1_train.txt file come from? Or how?

**Comment by JianghaiSCU** [comment]
请参考：https://github.com/JianghaiSCU/Diffusion-Low-Light/issues/12，txt文件需要根据自己的本地环境生成，所以我们无法提供，也可以对dataset.py进行修改以适应各位自己的设置.
