### ISSUE TITLE
LOLv1_train.txt and TypeError: get_loaders() got an unexpected keyword argument 'parse_patches'

### ISSUE THREAD

**Issue by gml100** [JianghaiSCU/Diffusion-Low-Light#21]
Hello, how did LOLv1_train.txt  come about? “TypeError: get_loaders() got an unexpected keyword argument 'parse_patches'”  error always appears when conducting an evaluation, how to fix it?

**Comment by qiqi77z** [comment]
Have you solved this problem?

**Comment by gml100** [comment]
No. I checked and found that the calling code for converting to. txt is missing. Can you please let me know if you have resolved this issue

**Comment by hammad97** [comment]
I think LOLv1_train.txt is a file which contains image names of all the images in our train / val dataset. I created my own txt file, here it is.
`1.png
10.png
100.png
101.png
102.png
103.png
104.png
105.png
106.png
107.png
109.png
110.png
111.png
112.png
113.png
114.png
115.png
116.png
117.png
118.png
119.png
12.png
120.png
121.png
122.png
123.png
124.png
125.png
126.png
127.png
128.png
129.png
13.png
130.png
131.png
132.png
135.png
136.png
137.png
138.png
139.png
14.png
140.png
141.png
142.png
143.png
144.png
145.png
146.png
147.png
149.png
15.png
150.png
151.png
152.png
154.png
157.png
159.png
16.png
160.png
162.png
167.png
169.png
17.png
171.png
172.png
173.png
174.png
175.png
176.png
179.png
18.png
180.png
183.png
184.png
185.png
186.png
187.png
188.png
189.png
191.png
193.png
194.png
195.png
196.png
198.png
199.png
2.png
200.png
201.png
202.png
203.png
204.png
206.png
207.png
209.png
21.png
210.png
211.png
212.png
213.png
215.png
216.png
219.png
22.png
220.png
221.png
222.png
225.png
227.png
228.png
229.png
23.png
230.png
231.png
232.png
233.png
235.png
236.png
237.png
238.png
239.png
24.png
240.png
241.png
242.png
243.png
244.png
246.png
247.png
248.png
249.png
25.png
250.png
251.png
252.png
253.png
254.png
257.png
258.png
259.png
26.png
260.png
261.png
262.png
263.png
264.png
265.png
267.png
27.png
28.png
328.png
33.png
330.png
342.png
344.png
35.png
36.png
38.png
39.png
40.png
42.png
43.png
44.png
45.png
450.png
46.png
460.png
464.png
468.png
469.png
47.png
470.png
471.png
472.png
473.png
474.png
475.png
476.png
477.png
478.png
479.png
48.png
480.png
481.png
482.png
483.png
484.png
485.png
486.png
487.png
488.png
489.png
490.png
491.png
492.png
493.png
494.png
495.png
496.png
497.png
498.png
499.png
5.png
50.png
500.png
501.png
502.png
504.png
505.png
506.png
507.png
508.png
51.png
511.png
512.png
514.png
515.png
517.png
52.png
523.png
524.png
525.png
526.png
527.png
528.png
529.png
53.png
530.png
531.png
532.png
533.png
534.png
535.png
537.png
538.png
539.png
54.png
540.png
541.png
542.png
543.png
544.png
545.png
546.png
547.png
548.png
549.png
55.png
550.png
551.png
552.png
553.png
554.png
555.png
556.png
557.png
558.png
559.png
56.png
560.png
561.png
562.png
563.png
564.png
565.png
566.png
567.png
568.png
569.png
57.png
570.png
571.png
572.png
573.png
574.png
575.png
576.png
578.png
579.png
58.png
580.png
583.png
585.png
586.png
587.png
588.png
59.png
590.png
591.png
592.png
593.png
594.png
595.png
596.png
597.png
598.png
6.png
60.png
600.png
601.png
604.png
605.png
606.png
607.png
608.png
609.png
61.png
610.png
611.png
612.png
613.png
614.png
615.png
616.png
617.png
62.png
620.png
621.png
622.png
623.png
624.png
625.png
626.png
627.png
628.png
629.png
63.png
630.png
633.png
634.png
637.png
638.png
639.png
64.png
640.png
641.png
642.png
643.png
644.png
645.png
646.png
647.png
648.png
649.png
650.png
651.png
653.png
654.png
655.png
658.png
659.png
660.png
661.png
662.png
663.png
664.png
665.png
666.png
667.png
668.png
669.png
67.png
670.png
671.png
674.png
675.png
676.png
677.png
678.png
679.png
68.png
680.png
681.png
682.png
683.png
684.png
685.png
686.png
687.png
688.png
689.png
69.png
690.png
691.png
692.png
693.png
694.png
695.png
696.png
697.png
698.png
699.png
70.png
700.png
701.png
702.png
703.png
704.png
708.png
709.png
710.png
711.png
712.png
713.png
714.png
715.png
716.png
717.png
718.png
719.png
720.png
721.png
722.png
723.png
724.png
725.png
726.png
727.png
728.png
729.png
73.png
730.png
731.png
732.png
733.png
734.png
736.png
737.png
738.png
739.png
74.png
740.png
741.png
743.png
744.png
745.png
746.png
747.png
748.png
75.png
750.png
751.png
752.png
757.png
758.png
759.png
76.png
760.png
761.png
762.png
763.png
764.png
765.png
766.png
769.png
77.png
770.png
771.png
772.png
773.png
774.png
775.png
776.png
777.png
778.png
779.png
78.png
780.png
781.png
782.png
783.png
784.png
785.png
786.png
787.png
788.png
789.png
79.png
80.png
81.png
82.png
83.png
84.png
86.png
87.png
88.png
89.png
9.png
91.png
92.png
93.png
94.png
95.png
96.png
97.png
98.png
99.png
`

**Comment by gml100** [comment]
好哒，谢谢你，我试一试



你是一树一树的花开
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JianghaiSCU/Diffusion-Low-Light"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月25日(星期一) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JianghaiSCU/Diffusion-Low-Light] LOLv1_train.txt and TypeError: get_loaders() got an unexpected keyword argument 'parse_patches' (Issue #21)





 
I think LOLv1_train.txt is a file which contains image names of all the images in our train / val dataset. I created my own txt file, here it is.
 1.png 10.png 100.png 101.png 102.png 103.png 104.png 105.png 106.png 107.png 109.png 110.png 111.png 112.png 113.png 114.png 115.png 116.png 117.png 118.png 119.png 12.png 120.png 121.png 122.png 123.png 124.png 125.png 126.png 127.png 128.png 129.png 13.png 130.png 131.png 132.png 135.png 136.png 137.png 138.png 139.png 14.png 140.png 141.png 142.png 143.png 144.png 145.png 146.png 147.png 149.png 15.png 150.png 151.png 152.png 154.png 157.png 159.png 16.png 160.png 162.png 167.png 169.png 17.png 171.png 172.png 173.png 174.png 175.png 176.png 179.png 18.png 180.png 183.png 184.png 185.png 186.png 187.png 188.png 189.png 191.png 193.png 194.png 195.png 196.png 198.png 199.png 2.png 200.png 201.png 202.png 203.png 204.png 206.png 207.png 209.png 21.png 210.png 211.png 212.png 213.png 215.png 216.png 219.png 22.png 220.png 221.png 222.png 225.png 227.png 228.png 229.png 23.png 230.png 231.png 232.png 233.png 235.png 236.png 237.png 238.png 239.png 24.png 240.png 241.png 242.png 243.png 244.png 246.png 247.png 248.png 249.png 25.png 250.png 251.png 252.png 253.png 254.png 257.png 258.png 259.png 26.png 260.png 261.png 262.png 263.png 264.png 265.png 267.png 27.png 28.png 328.png 33.png 330.png 342.png 344.png 35.png 36.png 38.png 39.png 40.png 42.png 43.png 44.png 45.png 450.png 46.png 460.png 464.png 468.png 469.png 47.png 470.png 471.png 472.png 473.png 474.png 475.png 476.png 477.png 478.png 479.png 48.png 480.png 481.png 482.png 483.png 484.png 485.png 486.png 487.png 488.png 489.png 490.png 491.png 492.png 493.png 494.png 495.png 496.png 497.png 498.png 499.png 5.png 50.png 500.png 501.png 502.png 504.png 505.png 506.png 507.png 508.png 51.png 511.png 512.png 514.png 515.png 517.png 52.png 523.png 524.png 525.png 526.png 527.png 528.png 529.png 53.png 530.png 531.png 532.png 533.png 534.png 535.png 537.png 538.png 539.png 54.png 540.png 541.png 542.png 543.png 544.png 545.png 546.png 547.png 548.png 549.png 55.png 550.png 551.png 552.png 553.png 554.png 555.png 556.png 557.png 558.png 559.png 56.png 560.png 561.png 562.png 563.png 564.png 565.png 566.png 567.png 568.png 569.png 57.png 570.png 571.png 572.png 573.png 574.png 575.png 576.png 578.png 579.png 58.png 580.png 583.png 585.png 586.png 587.png 588.png 59.png 590.png 591.png 592.png 593.png 594.png 595.png 596.png 597.png 598.png 6.png 60.png 600.png 601.png 604.png 605.png 606.png 607.png 608.png 609.png 61.png 610.png 611.png 612.png 613.png 614.png 615.png 616.png 617.png 62.png 620.png 621.png 622.png 623.png 624.png 625.png 626.png 627.png 628.png 629.png 63.png 630.png 633.png 634.png 637.png 638.png 639.png 64.png 640.png 641.png 642.png 643.png 644.png 645.png 646.png 647.png 648.png 649.png 650.png 651.png 653.png 654.png 655.png 658.png 659.png 660.png 661.png 662.png 663.png 664.png 665.png 666.png 667.png 668.png 669.png 67.png 670.png 671.png 674.png 675.png 676.png 677.png 678.png 679.png 68.png 680.png 681.png 682.png 683.png 684.png 685.png 686.png 687.png 688.png 689.png 69.png 690.png 691.png 692.png 693.png 694.png 695.png 696.png 697.png 698.png 699.png 70.png 700.png 701.png 702.png 703.png 704.png 708.png 709.png 710.png 711.png 712.png 713.png 714.png 715.png 716.png 717.png 718.png 719.png 720.png 721.png 722.png 723.png 724.png 725.png 726.png 727.png 728.png 729.png 73.png 730.png 731.png 732.png 733.png 734.png 736.png 737.png 738.png 739.png 74.png 740.png 741.png 743.png 744.png 745.png 746.png 747.png 748.png 75.png 750.png 751.png 752.png 757.png 758.png 759.png 76.png 760.png 761.png 762.png 763.png 764.png 765.png 766.png 769.png 77.png 770.png 771.png 772.png 773.png 774.png 775.png 776.png 777.png 778.png 779.png 78.png 780.png 781.png 782.png 783.png 784.png 785.png 786.png 787.png 788.png 789.png 79.png 80.png 81.png 82.png 83.png 84.png 86.png 87.png 88.png 89.png 9.png 91.png 92.png 93.png 94.png 95.png 96.png 97.png 98.png 99.png

**Comment by Rehgar3** [comment]
Have u solved it? I still got same error after adding txts of train and val.
