### ISSUE TITLE
训练期间启动的测试结果与训练结束之后加载权重的测试结果不一致

### ISSUE THREAD

**Issue by Shecyy** [JianghaiSCU/Diffusion-Low-Light#23]
作者，您好。感谢您开源了代码。我用您的代码去重新训练。发现在训练期间启动测试得到的结果较好。但是在所有训练epoch结束之后，用保存的权重去推理结果差的很多。请问这是什么原因哇？是需要在evaluate.py里面需要修改默认的参数设置吗？

**Comment by JianghaiSCU** [comment]
这个应该是seed的问题，你可以尝试在训练的时候把random sample的noise也存下来就能复现一样的结果.
