### ISSUE TITLE
About Loading Datasets

### ISSUE THREAD

**Issue by jacksonz0610** [JianghaiSCU/Diffusion-Low-Light#3]
I met some diffuculties on loading the datasets. Your code and datasets may not match well. I don't know where the dataset should be placed and how to load the dataset successfully. Could you give me more tips on running this code?

**Comment by JianghaiSCU** [comment]
You should make some modifications to the dataloader to load your customized data.  We formulate the datasets as txt files that contain only the path of the low-light images, such as low/1.png. For example, if you use the LOLv1 dataset for training and evaluation, you will need a LOLv1_train.txt and a LOLv1_val.txt.
