### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [JianghaiSCU/Diffusion-Low-Light#8]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.

- Converted ONNX + TFLite
  https://github.com/PINTO0309/PINTO_model_zoo/tree/main/418_Diffusion-Low-Light

Thank you.

**Comment by JianghaiSCU** [comment]
Thanks for your contribution, our model follows the MIT license.

**Comment by PINTO0309** [comment]
Thank you!
